portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('portfolioapp.urls','portfolioapp'), namespace='portfolioapp'))
]

portfolioapp/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

portfolioapp/models.py
from django.db import models

# Create your models here.

class aboutme(models.Model):
    Name = models.CharField(max_length=50)
    Title = models.CharField(max_length=50)
    DateofBirth = models.DateField()
    Address = models.CharField(max_length=50)
    Email = models.EmailField(max_length=254)
    Github = models.CharField(max_length=50)

    def __str__(self):
        return "{}. {}".format(self.id, self.Name)

class experience(models.Model):
    Years = models.CharField(max_length=50)
    Position = models.CharField(max_length=100)
    Office = models.CharField(max_length=40)
    Description = models.TextField()

    def __str__(self):
        return "{}. {}".format(self.id, self.Position)

class skill(models.Model):
    skills = models.CharField(max_length=100)

    icon_type = {
        ('flaticon-ideas','flaticon-ideas'),
        ('flaticon-flasks','flaticon-flasks'),
        ('flaticon-analysis','flaticon-analysis'),
        ('flaticon-ux-design','flaticon-ux-design'),
        ('flaticon-web-design','flaticon-web-design'),
        ('flaticon-idea','flaticon-idea'),
        ('flaticon-innovation','flaticon-innovation'),
    }

    icon = models.CharField(max_length=100, choices=icon_type, default='flaticon-ideas')

    def __str__(self):
        return "{}. {}".format(self.id, self.skills)

portfolio/views.py
from django.shortcuts import render

def index(request):
    context = {

    }
    return render(request, 'index.html', context)

portfolioapp/views.py
from django.shortcuts import render
from .models import aboutme, experience, skill

def index(request):


    about = aboutme.objects.all()
    myexperience = experience.objects.all()
    myskill = skill.objects.all()

    context = {
        'aboutme':about,
        'experience':myexperience,
        'skill':myskill,
    }
    return render(request, 'portfolioapp/index.html', context)

portfolioapp/templates/portfolioapp/index.html
<!DOCTYPE html>
<html lang="en">

	{% load static %}

  <head>
    <title>Gresiandra - Portfolio Website</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	
  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'portfolioapp:index' %}">myportfolio.</a>
	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav nav ml-auto">
	          <li class="nav-item"><a href="#home-section" class="nav-link"><span>Home</span></a></li>
	          <li class="nav-item"><a href="#about-section" class="nav-link"><span>About</span></a></li>
	          <li class="nav-item"><a href="#resume-section" class="nav-link"><span>Experience</span></a></li>
	          <li class="nav-item"><a href="#skills-section" class="nav-link"><span>Skills</span></a></li>
	          <li class="nav-item"><a href="#contact-section" class="nav-link"><span>Contact</span></a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>

	  {% block main %}

		<section class="hero-wrap js-fullheight" data-stellar-background-ratio="0.5" style="background-image:url(/static/images/backgrounds.jpg);">
			<div class="container mt-5">
			  <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center">
				<div class="col-md-12 ftco-animate mt-15 text-center">
				  <h1 class="mb-3 bread">Gresiandra Putra</h1>
				  <h4 class="mb-4 breadcrumbs">I am a Web Developer</h4>
				  <p><a href="mailto:gresiandra@gmail.com" class="btn btn-primary py-3 px-4">Email me</a> <a href="https://www.linkedin.com/in/gresiandra-putra-972b4120/" class="btn btn-white btn-outline-white py-3 px-4">My LinkedIn</a></p>
				</div>
			  </div>
			</div>
			
		  </section>
		

    </section>

    <section class="ftco-about img ftco-section ftco-no-pb" id="about-section">
    	<div class="container">
    		<div class="row d-flex">
    			<div class="col-md-6 col-lg-5 d-flex">
    				<div class="img-about img d-flex align-items-stretch">
    					<div class="overlay"></div>
	    				<div class="img d-flex align-self-stretch align-items-center" style="background-image:url(/static/images/me.png);">
	    				</div>
    				</div>
    			</div>
    			<div class="col-md-6 col-lg-7 pl-lg-5 pb-5">
    				<div class="row justify-content-start pb-3">
		          <div class="col-md-12 heading-section ftco-animate">
		          	<h1 class="big">About</h1>
		            <h2 class="mb-4">About Me</h2>
					<p>“The snow goose need not bathe to make itself white. Neither need you do anything but be yourself.”</p>
					<p>― Lao Tzu, Philosopher</p>					
					
					{% for me in aboutme %}

						<ul class="about-info mt-4 px-md-0 px-2">
							<li class="d-flex"><span>Name:</span> <span>{{me.Name}}</span></li>
							<li class="d-flex"><span>Degree:</span> <span>{{me.Title}}</span></li>
							<li class="d-flex"><span>Date of birth:</span> <span>{{me.DateofBirth}}</span></li>
							<li class="d-flex"><span>Address:</span> <span>{{me.Address}}</span></li>
							<li class="d-flex"><span>Email:</span> <span>{{me.Email}}</span></li>
							<li class="d-flex"><span>Github: </span> <span><a href="https://{{me.Github}}">{{me.Github}}</a></span></li>
						</ul>
						
					{% endfor %}
					

		          </div>
		        </div>
	          <div class="counter-wrap ftco-animate d-flex mt-md-5"> 
				<div class="text">
					<p class="mb-4">
						<h5><span>Here's My Curriculum Vitae</span></h5>
					</p>
					<p><a href="{% static 'file/CV.pdf' %}" download class="btn btn-primary py-3 px-3">Download CV</a></p>
				</div>
	          </div>
	        </div>
        </div>
    	</div>
    </section>

    <section class="ftco-section ftco-no-pb" id="resume-section">
    	<div class="container">
    		<div class="row justify-content-center pb-5">
          <div class="col-md-10 heading-section text-center ftco-animate">
          	<h1 class="big big-2">Experience</h1>
            <h2 class="mb-4">Experience</h2>
			<p>"Experience is what you get when you didn't get what you wanted. And experience is often the most valuable thing you have to offer."</p>
			<p>― Randy Pausch, The Last Lecture </p>
          </div>
        </div>
    		<div class="row">

				
				{% for myexperience in experience %}

					<div class="col-md-6">
						<div class="resume-wrap ftco-animate">
							<span class="date">{{myexperience.Years}}</span>
							<h2>{{myexperience.Position}}</h2>
							<span class="position">{{myexperience.Office}}</span>
							<p class="mt-4">{{myexperience.Description}}</p>
						</div>					
					</div>
					
				{% endfor %}
				
    		</div>
    	</div>
    </section>
		
	<section class="ftco-section" id="skills-section">
	<div class="container">
		<div class="row justify-content-center pb-5">
			<div class="col-md-12 heading-section text-center ftco-animate">
				<h1 class="big big-2">Skills</h1>
				<h2 class="mb-4">My Skills</h2>
				<p>“Every beginner possesses a great potential to be an expert in his or her chosen field.”</p>
				<p>― Lailah Gifty Akita, Think Great: Be Great! </p>
			</div>
		</div>
	
			<div class="row">
		
		{% for myskill in skill %}
			
				<div class="col-md-4 text-center d-flex ftco-animate">
					<a class="services-1">
						<span class="icon">
							<i class="{{myskill.icon}}"></i>
						</span>
						<div class="desc">
							<h3 class="mb-4">{{myskill.skills}}</h3>
						</div>
					</a>
				</div>

		{% endfor %}
		
			</div>
		</div>
	</section>

    <section class="ftco-section contact-section ftco-no-pb" id="contact-section">
      <div class="container">
      	<div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 heading-section text-center ftco-animate">
            <h1 class="big big-2">Contact</h1>
            <h2 class="mb-4">Contact Me</h2>
			<p>"People generally are more interested in my work when they get to know me. Serious collectors like to get not just a painting but a piece of the artist."</p>
			<p>― Toni Onley, Artist</p>
          </div>
        </div>
			
        <div class="row d-flex contact-info mb-5">
          <div class="col-md-6 col-lg-3 d-flex ftco-animate">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-map-signs"></span>
          		</div>
          		<h3 class="mb-4">Address</h3>
	            <p>Samarinda, East Kalimantan</p>
	          </div>
          </div>
          <div class="col-md-6 col-lg-3 d-flex ftco-animate">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-instagram"></span>
          		</div>
          		<h3 class="mb-4 ">Instagram</h3>
	            <p><a href="https://www.instagram.com/gresiandraputra/">@gresiandraputra</a></p>
	          </div>
          </div>
          <div class="col-md-6 col-lg-3 d-flex ftco-animate">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-twitter"></span>
          		</div>
          		<h3 class="mb-4 ">Twitter</h3>
	            <p><a href="https://twitter.com/gresiandra">@gresiandra</a></p>
	          </div>
          </div>
          <div class="col-md-6 col-lg-3 d-flex ftco-animate">
          	<div class="align-self-stretch box p-4 text-center">
          		<div class="icon d-flex align-items-center justify-content-center">
          			<span class="icon-paper-plane"></span>
          		</div>
          		<h3 class="mb-4">Email Address</h3>
	            <p><a href="mailto:gresiandra@gmail.com">gresiandra@gmail.com</a></p>
	          </div>
          </div>
		</div>
		
    </section>

        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by Colorlib
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
	  
  {% endblock main %}
	  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="	{% static 'js/jquery.min.js' %}"></script>
  <script src=" {% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src=" {% static 'js/popper.min.js' %}"></script>
  <script src="	{% static 'js/bootstrap.min.js' %}"></script>
  <script src="	{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src=" {% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="	{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="	{% static 'js/owl.carousel.min.js' %}"></script>
  <script src=" {% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="	{% static 'js/aos.js' %}"></script>
  <script src="	{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src=" {% static 'js/scrollax.min.js' %}"></script>
  <script src="	{% static 'js/main.js' %}"></script>
    
  </body>
</html>